import { afterAll, beforeAll, expect, test } from 'bun:test';
import { readFileSync } from 'node:fs';
import { basename, join } from 'node:path';
import { dataRoot, messagesPath } from '../../src/persistence/store';
import { threadKey } from '../../src/runtime/thread';
import { ensureImage } from '../../src/sandbox/docker';
import {
  type Agent,
  cleanupTempDataDir,
  createGoldenCallModel,
  deleteThread,
  DOCKER_PROVIDER_ACTIVE,
  mention,
  requireEnv,
  setupTempDataDirFromFixture,
  shutdown,
  startAgent,
  startTester,
  type Tester,
  waitForReply,
} from './helpers';

// The recorded scenario expects a sandbox provider that can run python +
// matplotlib reliably. Docker (with the local agenta-sandbox image) fits the
// bill; Fly trial machines may auto-stop or have DNS/egress issues that flake
// the live share_file step. Set `SANDBOX_PROVIDER=docker` before `bun test`
// to run it.
const ENABLED = DOCKER_PROVIDER_ACTIVE;

let agent: Agent;
let tester: Tester;
let channel: string;
const createdThreads: string[] = [];

// Note on env at record time: the recording captures whatever model the
// developer's `.env` configures (`MODEL_NAME` / `MODEL_BASE_URL` /
// `MODEL_API_KEY`). The sandbox provider (`SANDBOX_PROVIDER`) is whatever the
// `.env` says — `src/sandbox/index.ts` resolves it at module load, before
// `beforeAll` can override. In replay mode the gateway is never invoked so
// model env is irrelevant; the sandbox still runs live, so docker or fly must
// be reachable. The recording is provider-agnostic — it only contains the
// model's request/response shape, no sandbox bytes.

beforeAll(async () => {
  if (!ENABLED) return;
  // Seed the temp home with the checked-in python-charts fixture so the
  // skills block lands in the system prompt. (#102)
  setupTempDataDirFromFixture(join(import.meta.dir, 'fixtures', 'python-charts-home'));
  channel = requireEnv('TEST_CHANNEL_ID');
  await ensureImage();
  // Note: each test calls `startAgent(callModel)` itself so the golden CallModel
  // is per-test (positional replay is scoped to one test's call sequence).
  tester = await startTester();
});

afterAll(async () => {
  if (!ENABLED) return;
  for (const ts of createdThreads) {
    await deleteThread(tester, agent, channel, ts);
  }
  if (agent) await shutdown(agent, tester);
  else await tester.socket.disconnect();
  cleanupTempDataDir();
});

test.skipIf(!ENABLED)(
  'loads and uses python-charts',
  async () => {
    const { callModel, flush } = createGoldenCallModel(
      basename(import.meta.path),
      'loads and uses python-charts',
    );
    agent = await startAgent(callModel);

    const threadTs = await mention(
      tester,
      agent.botUserId,
      channel,
      undefined,
      // The prompt has to be deterministic enough that re-records don't churn
      // wildly. Asking for a tiny bar chart with explicit values keeps the
      // model's behavior tight.
      'Please make a quick bar chart of [10, 30, 20, 50] and share it.',
    );
    createdThreads.push(threadTs);

    // Wait for the bot to post a final non-checklist reply. The predicate
    // must reject:
    //   - in-flight checklists (lines starting with "• ")
    //   - the bare file_share message generated by share_file (empty/very
    //     short text — Slack reports the file caption, not assistant prose)
    //   - the "thinking…" placeholder
    // and accept the assistant's final prose. We require at least 8 chars of
    // non-bullet text — enough to filter file_share, well under any plausible
    // real assistant final reply.
    const FINAL_TIMEOUT_MS = 240_000;
    const reply = await waitForReply(
      tester,
      channel,
      threadTs,
      agent.botUserId,
      (t) => !t.startsWith('• ') && !t.includes('thinking…') && t.length >= 8,
      { timeoutMs: FINAL_TIMEOUT_MS },
    );
    // Final reply rule: must NOT restate the filename (file-handling rules).
    expect(reply.toLowerCase()).not.toContain('.png');

    // The Slack thread should have at least one message with an uploaded file
    // attached (from share_file). File uploads can lag behind a `replies`
    // poll briefly, so we re-poll until either it shows up or we time out.
    let fileMsg: unknown;
    const deadline = Date.now() + 30_000;
    while (Date.now() < deadline) {
      const replies = await tester.web.conversations.replies({ channel, ts: threadTs });
      fileMsg = (replies.messages ?? []).find(
        (m) =>
          Array.isArray((m as { files?: unknown[] }).files) &&
          (m as { files: unknown[] }).files.length > 0,
      );
      if (fileMsg) break;
      await new Promise((r) => setTimeout(r, 500));
    }
    expect(fileMsg).toBeDefined();

    // Inspect the persisted JSONL: we expect tool_calls for read_file (loading
    // the skill), bash (running python), and share_file (uploading). Order
    // varies by model behavior; we only assert the set is present.
    const tk = threadKey(channel, threadTs);
    const jsonl = readFileSync(messagesPath(tk), 'utf8');
    const events = jsonl
      .split('\n')
      .filter((l) => l.length > 0)
      .map(
        (l) =>
          JSON.parse(l) as {
            source: string;
            type: string;
            payload: { name?: string; arguments_json?: string };
          },
      );
    const toolNames = events
      .filter((e) => e.source === 'assistant' && e.type === 'tool_call')
      .map((e) => e.payload.name ?? '');
    expect(toolNames).toContain('share_file');
    // bash is the standard path for python-charts; if the model used a
    // different code-execution route, the test recording captures whatever it
    // did and we don't second-guess it here.
    expect(toolNames.some((n) => n === 'bash' || n === 'write_file')).toBe(true);

    // The skills block should have been projected into the system prompt
    // (skills loading is a host-side step, distinct from whether the model
    // chose to read the SKILL.md — small prompts often don't need to).
    const sessionPath = `${dataRoot()}/${tk}/session.json`;
    const session = JSON.parse(readFileSync(sessionPath, 'utf8')) as { system_prompt?: string };
    expect(session.system_prompt ?? '').toContain('python-charts');

    await flush();
  },
  300_000,
);
