#!/usr/bin/env bun
// Rewrites ISSUES.md at the repo root from `gh issue list`. Run after any
// issue create / close / edit, or as part of the wrap-session skill.
//
// The index is grouped by state × primary label (phase / gotcha / proposed /
// other). Titles are the recall surface; the body lives on GitHub.

import { spawnSync } from 'node:child_process';
import { writeFileSync } from 'node:fs';
import { join } from 'node:path';

const REPO = 'eladb/agenta';
const PRIMARY_LABELS = ['phase', 'gotcha', 'proposed'] as const;
type PrimaryLabel = (typeof PRIMARY_LABELS)[number];

type Issue = {
  number: number;
  title: string;
  state: 'OPEN' | 'CLOSED';
  labels: Array<{ name: string }>;
};

function fetchIssues(): Issue[] {
  const res = spawnSync(
    'gh',
    [
      'issue',
      'list',
      '-R',
      REPO,
      '--state',
      'all',
      '--limit',
      '1000',
      '--json',
      'number,title,state,labels',
    ],
    { encoding: 'utf-8' },
  );
  if (res.status !== 0) {
    throw new Error(`gh issue list failed: ${res.stderr || res.stdout}`);
  }
  return JSON.parse(res.stdout) as Issue[];
}

function primary(issue: Issue): PrimaryLabel | 'other' {
  for (const l of issue.labels) {
    if ((PRIMARY_LABELS as readonly string[]).includes(l.name)) {
      return l.name as PrimaryLabel;
    }
  }
  return 'other';
}

function renderSection(title: string, items: Issue[]): string {
  if (items.length === 0) return '';
  const sorted = [...items].sort((a, b) => a.number - b.number);
  const lines = [`## ${title} (${items.length})`, ''];
  for (const i of sorted) {
    lines.push(`- #${i.number} — ${i.title}`);
  }
  return lines.join('\n');
}

function render(issues: Issue[]): string {
  const byBucket: Record<string, Issue[]> = {};
  for (const issue of issues) {
    const key = `${issue.state}:${primary(issue)}`;
    (byBucket[key] ??= []).push(issue);
  }

  const sections = [
    '# Issues index',
    '',
    '_Generated by `bun scripts/refresh-issues-index.ts`. Do not edit by hand._',
    // Open buckets first — that's where active work lives.
    renderSection('Open · gotcha', byBucket['OPEN:gotcha'] ?? []),
    renderSection('Open · proposed', byBucket['OPEN:proposed'] ?? []),
    renderSection('Open · phase', byBucket['OPEN:phase'] ?? []),
    renderSection('Open · other', byBucket['OPEN:other'] ?? []),
    renderSection('Closed · phase', byBucket['CLOSED:phase'] ?? []),
    renderSection('Closed · gotcha', byBucket['CLOSED:gotcha'] ?? []),
    renderSection('Closed · proposed', byBucket['CLOSED:proposed'] ?? []),
    renderSection('Closed · other', byBucket['CLOSED:other'] ?? []),
  ].filter((s) => s.length > 0);

  return `${sections.join('\n\n')}\n`;
}

function main(): void {
  const issues = fetchIssues();
  const body = render(issues);
  const path = join(import.meta.dir, '..', 'ISSUES.md');
  writeFileSync(path, body);
  console.log(`wrote ${path} — ${issues.length} issue(s)`);
}

main();
