#!/usr/bin/env bash
# Rewrites ISSUES.md at the repo root from `gh issue list`. Run after any
# issue create / close / edit, or as part of the wrap-session skill.
#
# The index is grouped by state × primary label (phase / gotcha / proposed /
# other). Titles are the recall surface; the body lives on GitHub.

set -euo pipefail

REPO="eladb/agenta"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
OUT="$SCRIPT_DIR/../ISSUES.md"

ISSUES_JSON="$(gh issue list -R "$REPO" --state all --limit 1000 \
  --json number,title,state,labels)"

TOTAL="$(echo "$ISSUES_JSON" | jq 'length')"

# Bucket each issue by "STATE:primary-label" where primary is the first of
# phase/gotcha/proposed found on the issue, else "other".
BUCKETED="$(echo "$ISSUES_JSON" | jq '
  map({
    number, title, state,
    bucket: (
      .state + ":" + (
        ([.labels[].name] | map(select(. == "phase" or . == "gotcha" or . == "proposed")))[0]
        // "other"
      )
    )
  })
  | sort_by(.number)
')"

render_section() {
  local title="$1" bucket="$2"
  local items count
  items="$(echo "$BUCKETED" | jq --arg b "$bucket" '[.[] | select(.bucket == $b)]')"
  count="$(echo "$items" | jq 'length')"
  [[ "$count" == "0" ]] && return 0
  echo
  echo "## $title ($count)"
  echo
  echo "$items" | jq -r '.[] | "- #\(.number) — \(.title)"'
}

{
  echo "# Issues index"
  echo
  echo "_Generated by \`scripts/refresh-issues-index.sh\`. Do not edit by hand._"
  # Open buckets first — that's where active work lives.
  render_section "Open · gotcha"    "OPEN:gotcha"
  render_section "Open · proposed"  "OPEN:proposed"
  render_section "Open · phase"     "OPEN:phase"
  render_section "Open · other"     "OPEN:other"
  render_section "Closed · phase"   "CLOSED:phase"
  render_section "Closed · gotcha"  "CLOSED:gotcha"
  render_section "Closed · proposed" "CLOSED:proposed"
  render_section "Closed · other"   "CLOSED:other"
} > "$OUT"

echo "wrote $OUT — $TOTAL issue(s)"
